

# =========================
#   网易实时买卖数据字段名称
# =========================
class TradeFieldWY():
    CODE = "code"
    NAME = "name"
    DATE = "date"
    TIME = "time"
    OPEN = "open"
    PREVIOUS_CLOSE = "previous_close"
    CURRENT = "current"
    HIGH = "high"
    LOW = "low"
    BUY1_VOLUME = "buy1_volume"
    BUY1_PRICE = "buy1_price"
    BUY2_VOLUME = "buy2_volume"
    BUY2_PRICE = "buy2_price"
    BUY3_VOLUME = "buy3_volume"
    BUY3_PRICE = "buy3_price"
    BUY4_VOLUME = "buy4_volume"
    BUY4_PRICE = "buy4_price"
    BUY5_VOLUME = "buy5_volume"
    BUY5_PRICE = "buy5_price"
    SELL1_VOLUME = "sell1_volume"
    SELL1_PRICE = "sell1_price"
    SELL2_VOLUME = "sell2_volume"
    SELL2_PRICE = "sell2_price"
    SELL3_VOLUME = "sell3_volume"
    SELL3_PRICE = "sell3_price"
    SELL4_VOLUME = "sell4_volume"
    SELL4_PRICE = "sell4_price"
    SELL5_VOLUME = "sell5_volume"
    SELL5_PRICE = "sell5_price"

class TradeFieldXL:
    NAME = "name"
    DATE = "date"
    TIME = "time"
    CODE = "code"
    OPEN = "open"
    PREVIOUS_CLOSE = "previous_close"
    CURRENT = "current"
    HIGH = "high"
    LOW = "low"
    BUY_PRICE = "buy_price"
    SELL_PRICE = "sell_price"
    DEAL_VOLUME = "deal_volume"
    DEAL_PRICE = "deal_price"
    BUY1_VOLUME = "buy1_volume"
    BUY1_PRICE = "buy1_price"
    BUY2_VOLUME = "buy2_volume"
    BUY2_PRICE = "buy2_price"
    BUY3_VOLUME = "buy3_volume"
    BUY3_PRICE = "buy3_price"
    BUY4_VOLUME = "buy4_volume"
    BUY4_PRICE = "buy4_price"
    BUY5_VOLUME = "buy5_volume"
    BUY5_PRICE = "buy5_price"
    SELL1_VOLUME = "sell1_volume"
    SELL1_PRICE = "sell1_price"
    SELL2_VOLUME = "sell2_volume"
    SELL2_PRICE = "sell2_price"
    SELL3_VOLUME = "sell3_volume"
    SELL3_PRICE = "sell3_price"
    SELL4_VOLUME = "sell4_volume"
    SELL4_PRICE = "sell4_price"
    SELL5_VOLUME = "sell5_volume"
    SELL5_PRICE = "sell5_price"
